export const projects = [
  {
    title: 'Blog',
    description: "Blog developed using laravel 8 + livewire, AdminLte was implemented as an admin template for creating posts. It has a CRUD of categories and tags. One-to-many and many-to-many relationships using Eloquent ORM, access policies, roles, and permissions. Mysql database.",
      image: '/images/blog.png',
      tags: ['Laravel', 'Mysql', 'Liveware', 'Tailwind', 'Bootsrapp'],
    source: 'https://github.com/cpandares/blod-admin',
    visit: '',
    id: 0,
  },
  {
    title: 'Posts-TDD',
    description: "CRUD of posts with laravel, focused on unit testing using TDD. Unit tests to verify its performance",
      image: '/images/livewire.png',
      tags: ['Laravel', 'Mysql', 'Liveware', 'Php Unit', 'Tailwind'],
    source: 'https://github.com/cpandares/tdd-laravel',
    visit: '',
    id: 1,
  },
  {
    title: 'Eccommerce-Headphones',
    description: "Eccomerce developed with React and NextJs as the framework, backend in sanity.io, has stripe integration in test mode so who can test it, animations with CSS.",
      image: '/images/next.png',
      tags: ['React', 'Nextjs', 'Css', 'Stripe'],
    source: 'https://github.com/cpandares/eccomerce',
    visit: 'https://eccomerce-git-main-cpandares.vercel.app/',
    id: 1,
  },
  {
    title: 'Ventmove',
    description: "Using React, Symfony, Mysql to create a platform to make for all users create a page and integrate your Online Store, Reservation and Collection System, Online Events, Ticket Sales, Contact Manager (CRM), Financing Campaigns, Blog and Much More.",
      image: '/images/vent.png',
      tags: ['Symfony', 'Mysql', 'React', 'Sass'],
    source: '',
    visit: 'https://ventmove.com/',
    id: 2,
  },
  {
    title: 'Rv advisor',
    description:"This start a simple e-commerce for users in USA, with Rv vehicles, providing the opportunity to insure their vehicles, offer road assistance, tire insurance, all under the payment of memberships (using stripe). Today it is a whole social network where users can upload their posts, like systems, chat. Today it continues to grow and add features..",
    image: '/images/rv.png',
    tags: ['Php', 'Js','Mysql'],
    source: '',
    visit: 'https://panel.thervadvisor.com/',
    id: 3,
  },
  {
    title: 'Mern Calendar',
    description: "This is a code repository for the corresponding to an app developed in react & mongoDb with the ability to create users, and add events with a calendar, start date, end date, validations, etc.",
      image: '/images/calendar.png',
      tags: ['React', 'MongoDb','Node', 'Express'],
    source: 'https://github.com/cpandares/calendar-react',
    visit: '',
    id: 4,
  },
  {
    title: 'Journal-app',
    description: "This is a code repository for the corresponding to one app developed in react, redux & firebase, where users can add notes from different memories, add images. Provide login with google.",
    image: '/images/journal.png',
    tags: ['React', 'Firebase', 'Redux'],
    source: 'https://github.com/cpandares/diario-react-18',
    visit: 'https://app-journalr.netlify.app/auth/login',
    id: 5,
  },
  {
    title: 'shop-app',
    description: "Eccomerce developed in React in frontend & sass for styles, is just a test with a api rest free, included axios for petitions http",
    image: '/images/screencapture.png',
    tags: ['React', 'Firebase', 'Sass', 'Axios'],
    source: 'https://github.com/cpandares/eccomerce-static',
    visit: 'https://shoppingc-app.netlify.app/',
    id: 6,
  },
  {
    title: 'Search gifs',
    description: "A simple search engine of gifs, using fetch for http petitions, and just css for the styles.",
    image: '/images/gifs.png',
    tags: ['React', 'Css', 'fetch'],
    source: 'https://github.com/cpandares/eccomerce-static',
    visit: 'https://cpandares.github.io/react-gift/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];